CONDA_BUILD_SYSROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk
bzip2: '1'
c_compiler: clang
c_compiler_version: '20'
c_stdlib: macosx_deployment_target
c_stdlib_version: '12.1'
channel_targets: defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
cxx_compiler_version: '20'
expat: '2'
extend_keys:
- ignore_build_only_deps
- ignore_version
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
gil_type: normal
ignore_build_only_deps:
- python
- numpy
libffi: '3.4'
lua: '5'
ncurses: '6'
numpy: '1.26'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
platform: osx-arm64
python: '3.13'
python_impl: cpython
r_base: '3.5'
readline: '8'
sqlite: '3'
target_platform: osx-arm64
tk: '8.6'
xz: '5'
zlib: '1.2'
